spring.application.name=ticket-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/tms
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin

spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

